version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql-expressjs-app-db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./dist/databases/mysql/db:/var/lib/mysql